shadowcaster: true
enabled: true
position:
  x: -20
  y: 0
  z: 0
direction:
  x: 1
  y: 0
  z: 0
type: POINT_LIGHT
attenuation:
  constant: 0
  linear: 0
  quadratic: 0.35

flicker: 0.075

color:
  ambient:
    red: 0.055
    green: 0.032
    blue: 0.023
    # red: 0.35
    # green: 0.35
    # blue: 0.35
    alpha: 0.25
  diffuse:
    red: 0.055
    green: 0.032
    blue: 0.023
    # red: 0.11
    # green: 0.0643137254901961
    # blue: 0.04679738562091503
    # red: 0.33
    # green: 0.1843137254901961
    # blue: 0.12679738562091503
    alpha: 0.75
  specular:
    red: 0
    green: 0
    blue: 0
    alpha: 0
