ambient:
  red:   1.0
  green: 1.0
  blue:  1.0
  alpha: 1.0

diffuse:
  red:   1.0
  green: 1.0
  blue:  1.0
  alpha: 1.0

specular:
  red:   0.0
  green: 0.0
  blue:  0.0
  alpha: 0.0

shininess: 10

layers:
  - type: Lighting

  - type: Texture
    path: /images/rock.png
    flip_y: false
    scale_x: 1.0
    scale_y: 1.0
    generate_mipmap: true
    min_filter: GL_LINEAR
    mag_filter: GL_LINEAR
    mipmap_hint: GL_DONT_CARE
    format: GL_RGBA
    data_type: GL_UNSIGNED_BYTE
    wrap_s: GL_REPEAT
    wrap_t: GL_REPEAT
    premultiply_alpha: false
    colorspace_conversion: true

  - type: NormalMap
    path: /images/rockNormal.png
    flip_y: false
    scale_x: 1.0
    scale_y: 1.0
    generate_mipmap: true
    min_filter: GL_LINEAR
    mag_filter: GL_LINEAR
    mipmap_hint: GL_DONT_CARE
    format: GL_RGBA
    data_type: GL_UNSIGNED_BYTE
    wrap_s: GL_REPEAT
    wrap_t: GL_REPEAT
    premultiply_alpha: false
    colorspace_conversion: true

  - type: Highlight
    

